CREATE TABLE user_roles_in_organizations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id BIGINT,
    user_id         BIGINT,
    role            VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_organizations_roles PRIMARY KEY (id)
);

ALTER TABLE user_roles_in_organizations
    ADD CONSTRAINT FK_ORGANIZATIONS_ROLES_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE user_roles_in_organizations
    ADD CONSTRAINT FK_ORGANIZATIONS_ROLES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);