CREATE TABLE programs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_public       BOOLEAN                                 NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    created_at      TIMESTAMP                               NOT NULL,
    updated_at      TIMESTAMP                               NOT NULL,
    title           VARCHAR(255),
    CONSTRAINT pk_programs PRIMARY KEY (id)
);

ALTER TABLE programs
    ADD CONSTRAINT FK_PROGRAMS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);