CREATE TABLE contents
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title    VARCHAR(255),
    subtitle VARCHAR(255),
    content  VARCHAR(255),
    CONSTRAINT pk_contents PRIMARY KEY (id)
);