CREATE TABLE contents_in_programs
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    program_id BIGINT,
    content_id BIGINT,
    position   INT,
    CONSTRAINT pk_contents_in_programs PRIMARY KEY (id)
);

ALTER TABLE contents_in_programs
    ADD CONSTRAINT FK_CONTENTS_IN_PROGRAMS_ON_CONTENT FOREIGN KEY (content_id) REFERENCES contents (id);

ALTER TABLE contents_in_programs
    ADD CONSTRAINT FK_CONTENTS_IN_PROGRAMS_ON_PROGRAM FOREIGN KEY (program_id) REFERENCES programs (id);